version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: debesheesen/movie-recommendation-system-frontend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: debesheesen/movie-recommendation-system-backend
    ports:
      - "8501:8501"
    depends_on:
      - backend
